name = "Onid"
license = "MIT"
licenselink = "https://github.com/xdinomode/onid/blob/master/LICENSE.md"
description = "Simple but robust theme."
homepage = "https://github.com/xDinomode/onid"
tags = ["blog", "simple"]
features = ["blog", "simple"]
min_version = 0.15

[author]
  name = "xDinomode"
  homepage = "https://dinosaurscode.xyz"

